# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/timing_constrain.xdc

# Block Designs: bd/bluex/bluex.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex || ORIG_REF_NAME==bluex} -quiet] -quiet

# IP: bd/bluex/ip/bluex_reg_wb_0_0/bluex_reg_wb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_reg_wb_0_0 || ORIG_REF_NAME==bluex_reg_wb_0_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_redirection_0_0/bluex_redirection_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_redirection_0_0 || ORIG_REF_NAME==bluex_redirection_0_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_demux_id_0_0/bluex_demux_id_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_demux_id_0_0 || ORIG_REF_NAME==bluex_demux_id_0_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_controller_id_0_0/bluex_controller_id_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_controller_id_0_0 || ORIG_REF_NAME==bluex_controller_id_0_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_aux_id_0_0/bluex_aux_id_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_aux_id_0_0 || ORIG_REF_NAME==bluex_aux_id_0_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_alu_ex_0_0/bluex_alu_ex_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_alu_ex_0_0 || ORIG_REF_NAME==bluex_alu_ex_0_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_reg_heap_id_0_0/bluex_reg_heap_id_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_reg_heap_id_0_0 || ORIG_REF_NAME==bluex_reg_heap_id_0_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_PC_0_0/bluex_PC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_PC_0_0 || ORIG_REF_NAME==bluex_PC_0_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_wrapper_mem_0_0/bluex_wrapper_mem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_wrapper_mem_0_0 || ORIG_REF_NAME==bluex_wrapper_mem_0_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_util_vector_logic_0_0/bluex_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_util_vector_logic_0_0 || ORIG_REF_NAME==bluex_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_util_vector_logic_1_0/bluex_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_util_vector_logic_1_0 || ORIG_REF_NAME==bluex_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/bluex/ip/bluex_util_vector_logic_0_1/bluex_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bluex_util_vector_logic_0_1 || ORIG_REF_NAME==bluex_util_vector_logic_0_1} -quiet] -quiet

# XDC: d:/MyWorks/Programs/Verilog/vivado/bluex/bluex.gen/sources_1/bd/bluex/bluex_ooc.xdc
